### Recommender Systems

In [1]:
import pandas as pd

In [3]:
reviews = pd.read_csv("https://s3.amazonaws.com/amazon-reviews-pds/tsv/sample_us.tsv", sep = '\t')

In [4]:
reviews.head()

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date
0,US,18778586,RDIJS7QYB6XNR,B00EDBY7X8,122952789,Monopoly Junior Board Game,Toys,5,0,0,N,Y,Five Stars,Excellent!!!,2015-08-31
1,US,24769659,R36ED1U38IELG8,B00D7JFOPC,952062646,56 Pieces of Wooden Train Track Compatible wit...,Toys,5,0,0,N,Y,Good quality track at excellent price,Great quality wooden track (better than some o...,2015-08-31
2,US,44331596,R1UE3RPRGCOLD,B002LHA74O,818126353,Super Jumbo Playing Cards by S&S Worldwide,Toys,2,1,1,N,Y,Two Stars,Cards are not as big as pictured.,2015-08-31
3,US,23310293,R298788GS6I901,B00ARPLCGY,261944918,Barbie Doll and Fashions Barbie Gift Set,Toys,5,0,0,N,Y,my daughter loved it and i liked the price and...,my daughter loved it and i liked the price and...,2015-08-31
4,US,38745832,RNX4EXOBBPN5,B00UZOPOFW,717410439,Emazing Lights eLite Flow Glow Sticks - Spinni...,Toys,1,1,1,N,Y,DONT BUY THESE!,Do not buy these! They break very fast I spun ...,2015-08-31

In [6]:
rev_df = pd.pivot(reviews, index = 'product_title', columns = 'customer_id', values = 'star_rating')

In [7]:
rev_df.shape

(49, 48)

In [8]:
rev_df.head()

customer_id,125518,128540,433677,1297934,1662075,2749569,5543658,6762003,7360347,11210951,...,41168357,42523709,43173394,43880421,44331596,44928701,45601416,47546726,47781982,52006292
product_title,,,,,,,,,,,,,,,,,,,,,
100 Foot Multicolor Pennant Banner,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
56 Pieces of Wooden Train Track Compatible with All Major Train Brands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alien Frontiers: Factions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AmiGami Fox and Owl Figure 2-Pack,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BCW - Deluxe Currency Slab - Regular Bill - Dollar / Currency Collecting Supplies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
rev_df.fillna(0, inplace = True)

In [10]:
rev_df.head()

customer_id,125518,128540,433677,1297934,1662075,2749569,5543658,6762003,7360347,11210951,...,41168357,42523709,43173394,43880421,44331596,44928701,45601416,47546726,47781982,52006292
product_title,,,,,,,,,,,,,,,,,,,,,
100 Foot Multicolor Pennant Banner,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
56 Pieces of Wooden Train Track Compatible with All Major Train Brands,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Alien Frontiers: Factions,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AmiGami Fox and Owl Figure 2-Pack,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BCW - Deluxe Currency Slab - Regular Bill - Dollar / Currency Collecting Supplies,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
from scipy.sparse import csr_matrix

In [14]:
rev_sparse = csr_matrix(rev_df)

In [11]:
from sklearn.metrics import pairwise_distances

In [16]:
dists = pairwise_distances(rev_sparse, metric = 'cosine')

In [19]:
dist_rev_df = pd.DataFrame(dists, index = rev_df.index, columns = rev_df.index)

In [21]:
dist_rev_df['Baby Einstein Octoplush'].nsmallest(10)

product_title
Baby Einstein Octoplush                                                                    0.0
100 Foot Multicolor Pennant Banner                                                         1.0
56 Pieces of Wooden Train Track Compatible with All Major Train Brands                     1.0
Alien Frontiers: Factions                                                                  1.0
AmiGami Fox and Owl Figure 2-Pack                                                          1.0
BCW - Deluxe Currency Slab - Regular Bill - Dollar / Currency Collecting Supplies          1.0
Barbie Doll and Fashions Barbie Gift Set                                                   1.0
Barkology Princess the Poodle Hand Puppet                                                  1.0
Big Bang Cosmic Pegasus (Pegasis) Metal 4D High Performance Generic Battling Top BB-105    1.0
Cards Against Humanity                                                                     1.0
Name: Baby Einstein Octoplush, dtype: float64

In [23]:
import numpy as np

In [24]:
np.random.choice(rev_df.index)

'Super Jumbo Playing Cards by S&S Worldwide'

In [25]:
def find_reviews():
    name = np.random.choice(rev_df.index)
    return dist_rev_df[name].nsmallest(10)

In [28]:
find_reviews()

product_title
AmiGami Fox and Owl Figure 2-Pack                                                          0.0
100 Foot Multicolor Pennant Banner                                                         1.0
56 Pieces of Wooden Train Track Compatible with All Major Train Brands                     1.0
Alien Frontiers: Factions                                                                  1.0
BCW - Deluxe Currency Slab - Regular Bill - Dollar / Currency Collecting Supplies          1.0
Baby Einstein Octoplush                                                                    1.0
Barbie Doll and Fashions Barbie Gift Set                                                   1.0
Barkology Princess the Poodle Hand Puppet                                                  1.0
Big Bang Cosmic Pegasus (Pegasis) Metal 4D High Performance Generic Battling Top BB-105    1.0
Cards Against Humanity                                                                     1.0
Name: AmiGami Fox and Owl Figure 2-Pack, dtype: float64

In [30]:
df = 1 - dist_rev_df

In [31]:
df.mean()

product_title
100 Foot Multicolor Pennant Banner                                                                                 0.020408
56 Pieces of Wooden Train Track Compatible with All Major Train Brands                                             0.020408
Alien Frontiers: Factions                                                                                          0.020408
AmiGami Fox and Owl Figure 2-Pack                                                                                  0.020408
BCW - Deluxe Currency Slab - Regular Bill - Dollar / Currency Collecting Supplies                                  0.020408
Baby Einstein Octoplush                                                                                            0.020408
Barbie Doll and Fashions Barbie Gift Set                                                                           0.020408
Barkology Princess the Poodle Hand Puppet                                                                          0.020408
Big Bang Cosmic Pegasus (Pegasis) Metal 4D High Performance Generic Battling Top BB-105                            0.020408
Cards Against Humanity                                                                                             0.020408
Claw Climber Goliath/ Disney's Gargoyles                                                                           0.020408
Disney Baby: Eeyore Large Plush                                                                                    0.020408
Disney Planes: Fire & Rescue Scoop & Spray Firefighter Dusty                                                       0.020408
Emazing Lights eLite Flow Glow Sticks - Spinning Light LED Toy                                                     0.020408
Fisher-Price Octonauts Shellington's On-The-Go Pod Toy                                                             0.020408
Franklin Sports MLB Fold Away Batting Tee                                                                          0.020408
Fun Express Insect Finger Puppets 12ct Toy                                                                         0.020408
Holy Stone F180C Mini RC Quadcopter Drone with Camera 2.4GHz 6-Axis Gyro Bonus Battery and 8 Blades                0.020408
Hot Wheels 48- Car storage Case With Easy Grip Carrying Case                                                       0.020408
Intex Mesh Lounge (Colors May Vary)                                                                                0.020408
Intex River Run I Sport Lounge, Inflatable Water Float, 53 in Diameter                                             0.020408
Klutz Sticker Design Studio: Create Your Own Custom Stickers Craft Kit                                             0.020408
LCR Dice Game (Red Chips)                                                                                          0.020408
LEGO Creative Tower Building Kit XXL 1600 Pieces 10664                                                             0.020408
Lalaloopsy Girls Basic Doll- Prairie Dusty Trails                                                                  0.020408
LeapFrog LeapTV Letter Factory Adventures Educational, Active Video Game                                           0.020408
Melissa & Doug Water Wow Coloring Book - Vehicles                                                                  0.020408
Minecraft Animal Toy (6-Pack)                                                                                      0.020408
Monopoly Junior Board Game                                                                                         0.020408
Monster High Haunted Student Spirits Porter Geiss Doll                                                             0.020408
New Age Scare Halloween Party Pumpkin and Bat Hanging Round Lantern Decoration, Paper, 9" Pack of 3                0.020408
Ocean Life Stamps Birthday Party Supplies Loot Bag Accessories 24 Pieces per Unit                                  0.020408
Paraboard - Parallel Charging Board for Lipos with EC5 Connectors                                                  0.020408
Peppa Pig 7 Wood Puzzles In Wooden Storage Box (styles will vary)                                                  0.020408
Pig Jumbo Foil Balloon                                                                                             0.020408
Pokemon - Double Dragon Energy (97/108) - XY Roaring Skies                                                         0.040816
Pokemon - Gyarados (31/113) - Legendary Treasures                                                                  0.040816
Seat Pets Car Seat Toy                                                                                             0.020408
Star Wars Clone Wars Clone Trooper Child's Deluxe Captain Rex Costume                                              0.020408
Super Jumbo Playing Cards by S&S Worldwide                                                                         0.020408
Team Losi 8IGHT-E RTR AVC Electric 4WD Buggy Vehicle (1/8 Scale)                                                   0.020408
Teenage Mutant Ninja Turtles T-Machines Tiger Claw in Safari Truck Diecast Vehicle                                 0.020408
The Game of Life Money and Asset Board Game, Fame Edition                                                          0.020408
WOW Toys Town Advent Calendar                                                                                      0.020408
Whiffer Sniffers Mystery Pack 1 Scented Backpack Clip                                                              0.020408
Winston Zeddmore & Ecto-1: Funko POP! Rides x Ghostbusters Vinyl Figure                                            0.020408
Yoga Joes - Green Army Men Toys                                                                                    0.020408
Yu-Gi-Oh! - Solemn Judgment (GLD5-EN045) - Gold Series: Haunted Mine - Limited Edition - Ghost/Gold Hybrid Rare    0.020408
ZuZo 2.4GHz 4 CH 6 Axis Gyro RC Quadcopter Drone with Camera & LED Lights, 38 x 38 x 7cm                           0.020408
dtype: float64

In [34]:
jokes = pd.read_excel('data/jester.xlsx', header = None)

In [35]:
jokes.head()

,0,1,2,3,4,5,6,7,8,9,...,149,150,151,152,153,154,155,156,157,158
0,1,99,99,99,99,99,99,99.0,99.0,99,...,99.0,99.0,99.00,99.00,99.0,99.0,99.0,99.0,99.00,99.00
1,1,99,99,99,99,99,99,99.0,99.0,99,...,99.0,99.0,99.00,99.00,99.0,99.0,99.0,99.0,99.00,99.00
2,4,99,99,99,99,99,99,99.0,99.0,99,...,99.0,99.0,99.00,99.00,99.0,99.0,99.0,99.0,99.00,99.00
3,47,99,99,99,99,99,99,99.0,99.0,99,...,99.0,99.0,5.61,-4.51,0.0,0.0,99.0,0.0,5.93,4.19
4,13,99,99,99,99,99,99,99.0,99.0,99,...,99.0,99.0,99.00,99.00,99.0,0.0,99.0,99.0,99.00,0.00

In [38]:
joke_info = pd.read_excel('data/Dataset4JokeSet.xlsx', header = None)

In [39]:
joke_info.head()

                                                   0
0  A man visits the doctor. The doctor says "I ha...
1  This couple had an excellent relationship goin...
2  Q. What's 200 feet long and has 4 teeth?   A. ...
3  Q. What's the difference between a man and a t...
4  Q.\tWhat's O. J. Simpson's Internet address?  ...

In [41]:
print(joke_info.iloc[2].values)

["Q. What's 200 feet long and has 4 teeth?   A. The front row at a Willie Nelson Concert."]

In [44]:
jokes = jokes.loc[jokes[0] > 10]

In [45]:
jokes.head()

,0,1,2,3,4,5,6,7,8,9,...,149,150,151,152,153,154,155,156,157,158
3,47,99,99,99,99,99,99,99.00,99.00,99,...,99.00,99.00,5.61,-4.51,0.00,0.00,99.00,0.00,5.93,4.19
4,13,99,99,99,99,99,99,99.00,99.00,99,...,99.00,99.00,99.00,99.00,99.00,0.00,99.00,99.00,99.00,0.00
5,33,99,99,99,99,99,99,99.00,99.00,99,...,99.00,3.19,99.00,0.00,3.41,99.00,-2.32,99.00,0.00,2.93
6,112,99,99,99,99,99,99,-4.45,7.54,99,...,-1.97,1.89,0.00,0.00,7.38,3.19,-9.33,-7.26,-9.13,-8.19
7,34,99,99,99,99,99,99,99.00,99.00,99,...,3.98,99.00,2.22,6.08,10.00,99.00,99.00,6.30,4.11,8.25

In [46]:
jokes.drop(0, axis = 1, inplace = True)

In [47]:
jokes = jokes + 5

In [48]:
jokes.head()

,1,2,3,4,5,6,7,8,9,10,...,149,150,151,152,153,154,155,156,157,158
3,104,104,104,104,104,104,104.00,104.00,104,104,...,104.00,104.00,10.61,0.49,5.00,5.00,104.00,5.00,10.93,9.19
4,104,104,104,104,104,104,104.00,104.00,104,104,...,104.00,104.00,104.00,104.00,104.00,5.00,104.00,104.00,104.00,5.00
5,104,104,104,104,104,104,104.00,104.00,104,104,...,104.00,8.19,104.00,5.00,8.41,104.00,2.68,104.00,5.00,7.93
6,104,104,104,104,104,104,0.55,12.54,104,104,...,3.03,6.89,5.00,5.00,12.38,8.19,-4.33,-2.26,-4.13,-3.19
7,104,104,104,104,104,104,104.00,104.00,104,104,...,8.98,104.00,7.22,11.08,15.00,104.00,104.00,11.30,9.11,13.25

In [50]:
jokes = jokes.replace(104, 0)

In [51]:
jokes.head()

,1,2,3,4,5,6,7,8,9,10,...,149,150,151,152,153,154,155,156,157,158
3,0,0,0,0,0,0,0.00,0.00,0,0,...,0.00,0.00,10.61,0.49,5.00,5.00,0.00,5.00,10.93,9.19
4,0,0,0,0,0,0,0.00,0.00,0,0,...,0.00,0.00,0.00,0.00,0.00,5.00,0.00,0.00,0.00,5.00
5,0,0,0,0,0,0,0.00,0.00,0,0,...,0.00,8.19,0.00,5.00,8.41,0.00,2.68,0.00,5.00,7.93
6,0,0,0,0,0,0,0.55,12.54,0,0,...,3.03,6.89,5.00,5.00,12.38,8.19,-4.33,-2.26,-4.13,-3.19
7,0,0,0,0,0,0,0.00,0.00,0,0,...,8.98,0.00,7.22,11.08,15.00,0.00,0.00,11.30,9.11,13.25

In [52]:
jokes.T

,3,4,5,6,7,9,10,23,31,35,...,7670,7672,7676,7677,7682,7686,7690,7694,7696,7697
1,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
2,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
3,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
4,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
5,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,5.00,5.0,0.00,8.19,0.00,0.00,7.34,0.00,0.0,0.00,...,10.04,6.12,0.0,0.00,0.28,-3.11,-0.57,0.0,8.50,5.00
155,0.00,0.0,2.68,-4.33,0.00,0.00,0.00,9.39,0.0,0.00,...,0.00,0.00,0.0,5.00,0.28,-3.92,3.41,5.0,11.26,7.97
156,5.00,0.0,0.00,-2.26,11.30,0.00,0.00,2.48,0.0,0.00,...,0.00,0.00,0.0,5.00,1.21,-4.49,1.71,5.0,0.00,5.57
157,10.93,0.0,5.00,-4.13,9.11,0.00,0.00,0.00,0.0,0.00,...,0.00,0.00,0.0,6.95,8.42,-0.91,1.42,5.0,2.34,5.00
158,9.19,5.0,7.93,-3.19,13.25,1.32,2.66,3.54,5.0,-2.28,...,0.00,3.78,0.0,5.00,7.73,0.00,5.41,0.0,5.65,5.00

In [55]:
jokest = jokes.T
jokest.index = joke_info.values

In [56]:
jokest.head()

,3,4,5,6,7,9,10,23,31,35,...,7670,7672,7676,7677,7682,7686,7690,7694,7696,7697
"(A man visits the doctor. The doctor says ""I have bad news for you.You have cancer and Alzheimer's disease"". The man replies ""Well,thank God I don't have cancer!"",)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(This couple had an excellent relationship going until one day he came home from work to find his girlfriend packing. He asked her why she was leaving him and she told him that she had heard awful things about him. ""What could they possibly have said to make you move out?"" ""They told me that you were a pedophile."" He replied, ""That's an awfully big word for a ten year old."",)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(Q. What's 200 feet long and has 4 teeth? A. The front row at a Willie Nelson Concert.,)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(Q. What's the difference between a man and a toilet? A. A toilet doesn't follow you around after you use it.,)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"(Q.\tWhat's O. J. Simpson's Internet address? A.\tSlash, slash, backslash, slash, slash, escape.,)",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [57]:
joke_sparse = csr_matrix(jokest)

In [60]:
joke_recs = 1 - pairwise_distances(joke_sparse, metric = 'cosine')

In [62]:
rev_df = pd.DataFrame(joke_recs, index = joke_info.values, columns = joke_info.values)

In [66]:
def find_jokes():
    name = np.random.choice(joke_info[0].values)
    return rev_df[name].nsmallest(10)

In [80]:
a = rev_df.sum().nlargest(5).index[0]

In [84]:
rev_df[a].nlargest(6).tail(5)

(A new business was opening and one of the owner's friends wanted to send him flowers for the occasion. They arrived at the new business site and the owner read the card, "Rest in Peace." The owner was angry and called the florist to complain. After he had told the florist of the obvious mistake and how angry he was, the florist replied, "Sir, I'm really sorry for the mistake, but rather than getting angry, you should imagine this: somewhere there is a funeral taking place today, and they have flowers with a note saying, 'Congratulations on your new location!'",)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               0.658253
(There was an engineer who had an exceptional gift for fixing all  things mechanical.  After serving his company loyally for over 30  years, he happily retired.  Several years later the company contacted  him regarding a seemingly impossible problem they were having with  one of their multi-million dollar machines. They had tried everything and  everyone else to get the machine fixed, but to no avail.  In  desperation, they called on the retired engineer who had solved so  many of their problems in the past. The engineer reluctantly took the challenge.  He spent a day studying  the huge machine.  At the end of the day, he marked a small "x" in  chalk on a particular component of the machine and proudly stated,  "This is where your problem is". The part was replaced and the machine worked perfectly again. The  company received a bill for $50,000 from the engineer for his  service.They demanded an itemized accounting of his charges. The  engineer responded briefly: One chalk mark                       $1  Knowing where to put it            $49,999 It was paid in full and the engineer retired again in peace.,)    0.649424
(A teacher is explaining to her class how different languages use  negatives differently.  She says, "In all languages, a positive followed by a negative or a negative followed by a positive makes a negative.  In some languages, two negatives together make a positive, while in others they make a negative.  But in no language do two positives make a negative."    One of the students puts up his hand and says, "Yeah, right.",)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            0.636210
(A preist, a 12-year-old kid, and the smartest guy in the world are on a plane. The pilot screams, "The plane is going down! You have to jump!" He then grabs a parachute and jumps off, leaving only two more parachutes on the plane. The smartest guy in the world says, "I have to go. I mean, I'm the smartest guy in the world!" He grabs a parachute, and jumps. The priest then looks at the 12-year-old kid, and says, "Go, my son. You have a long life to live." The kid calmly responds: "Dude, chill. We'll be fine. The 'smartest guy in the world' took my backpack.",)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  0.625575
(Reaching the end of a job interview, the human resources person asked a young engineer fresh out of Stanford,  "And what starting salary were you looking for?"  The engineer said, "In the neighborhood of $125,000 a year, depending on the benefits package."  The interviewer said, "Well, what would you say to a package of 5-weeks  vacation, 14 paid holidays, full medical and dental, company matching  retirement fund to 50% of salary, and a company car leased every 2 years -  say, a red Corvette?"  The Engineer sat up straight and said, "Wow! Are you kidding?"  And the interviewer replied, "Yeah, but you started it.",)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        0.624375
Name: (In an interview with David Letterman, Carter passed along an anecdote of a translation problem in Japan. Carter was speaking at a business lunch in Tokyo, where he decided to open his speech with a brief joke. He told the joke, then waited for the translator to announce the Japanese version. Even though the story was quite short, Carter was surprised by how quickly the interpreter was able to re-tell it. Even more impressive was the reaction from the crowd. Carter thought the story was cute, but not outright hilarious, yet the crowd broke right up. Carter was very flattered. After the speech, Carter wanted to meet the translator to ask him how he told the joke. Perhaps there is better way to tell the joke? When Carter asked how the joke had been told in Japanese, the translator responded, "I told them, 'President Carter has told a very funny joke. Please laugh now.'",), dtype: float64

### Trying Surprise

- Load in data to dataframe
- Create trainset
- Use any algorithm's `.fit` method

In [85]:
import surprise

In [86]:
reviews = pd.read_csv("https://s3.amazonaws.com/amazon-reviews-pds/tsv/sample_us.tsv", sep = '\t')

In [87]:
reviews.head()

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date
0,US,18778586,RDIJS7QYB6XNR,B00EDBY7X8,122952789,Monopoly Junior Board Game,Toys,5,0,0,N,Y,Five Stars,Excellent!!!,2015-08-31
1,US,24769659,R36ED1U38IELG8,B00D7JFOPC,952062646,56 Pieces of Wooden Train Track Compatible wit...,Toys,5,0,0,N,Y,Good quality track at excellent price,Great quality wooden track (better than some o...,2015-08-31
2,US,44331596,R1UE3RPRGCOLD,B002LHA74O,818126353,Super Jumbo Playing Cards by S&S Worldwide,Toys,2,1,1,N,Y,Two Stars,Cards are not as big as pictured.,2015-08-31
3,US,23310293,R298788GS6I901,B00ARPLCGY,261944918,Barbie Doll and Fashions Barbie Gift Set,Toys,5,0,0,N,Y,my daughter loved it and i liked the price and...,my daughter loved it and i liked the price and...,2015-08-31
4,US,38745832,RNX4EXOBBPN5,B00UZOPOFW,717410439,Emazing Lights eLite Flow Glow Sticks - Spinni...,Toys,1,1,1,N,Y,DONT BUY THESE!,Do not buy these! They break very fast I spun ...,2015-08-31

In [89]:
#userID, reviewID, rating
rev_df = reviews[['customer_id', 'review_id', 'star_rating']]

In [90]:
rev_df.columns = ['userID', 'itemID', 'rating']

In [92]:
reviews['star_rating'].describe()

count    49.000000
mean      4.183673
std       1.364329
min       1.000000
25%       4.000000
50%       5.000000
75%       5.000000
max       5.000000
Name: star_rating, dtype: float64

In [102]:
from surprise import Reader
from surprise import Dataset
from surprise.model_selection import cross_validate

In [103]:
reader = Reader(rating_scale=(1, 5))

In [109]:
data = Dataset.load_from_df(rev_df, reader)

In [110]:
train = data.build_full_trainset()

In [111]:
from surprise import SVD

In [112]:
algo = SVD()

In [113]:
cross_validate(algo, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    1.1039  2.0706  1.0185  1.5663  1.0078  1.3534  0.4132
MAE (testset)     1.0306  1.6872  1.0182  1.1538  0.8472  1.1474  0.2870
Fit time          0.00    0.00    0.00    0.00    0.00    0.00    0.00
Test time         0.00    0.00    0.00    0.00    0.00    0.00    0.00

{'test_rmse': array([1.10390721, 2.07061403, 1.01848414, 1.56628683, 1.00778222]),
 'test_mae': array([1.03055848, 1.68717949, 1.01824224, 1.15384615, 0.84722222]),
 'fit_time': (0.001911163330078125,
  0.0017421245574951172,
  0.0018012523651123047,
  0.0017478466033935547,
  0.0018610954284667969),
 'test_time': (6.29425048828125e-05,
  5.1021575927734375e-05,
  5.7697296142578125e-05,
  5.1975250244140625e-05,
  4.982948303222656e-05)}

In [114]:
algo.fit(train)